language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kermant11/docker-demo -f Dockerfile.dev .

script:
   - docker run -e CI=true kermant11/docker-demo npm run test


#------------------- deploy to AWS

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: docker
  env: "Docker-env"
  bucket_name: "nejake meno"
  bucket_path: "nejaka cesta"
  on:
    branch: master