language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kermant11/docker-demo -f Dockerfile.dev .

script:
   - docker run -e CI=true kermant11/docker-demo npm run test